image: Visual Studio 2019

# Adds "+build.XXX" to MinVer's build metadata
environment:
  MINVERBUILDMETADATA: build.%APPVEYOR_BUILD_NUMBER%

# AppVeyor's displaye version, will get updated by MSBuild target
version: '{build}'

configuration: Release

before_build:
  - dotnet restore

build:
  parallel: true
  verbosity: minimal

test_script:
  - dotnet test

artifacts:
  - path: ./**/*.nupkg
